### ISSUE TITLE
Make a Jupyter Python Notebook front end page or two

### ISSUE THREAD

**Issue by goatchurchprime** [OCHA-DAP/hdxscraper-chathamhouse#1]
A couple of notebook pages that imported these scripts would make it possible to plot graphs, visualize maps and other data, and interact with the parameters from within this interface.  Such worked example pages would be pleasingly rendered by the github website.  

Seems pretty obvious that most of the code for the model could have been developed in Jupyter (possibly using sympy for the mathematical formlas) before being copied into python libraries where they could be used by cleaner notebooks.  

For more, see some examples of the way this news organization does it:
    https://github.com/BuzzFeedNews/2016-12-medicare-claims-analysis/blob/master/notebooks/medicare-claims-analysis.ipynb

**Comment by mcarans** [comment]
Thanks for your feedback. I made a Pandas version of the model for comparison previously, but felt that it complicated unit testing, so reverted to plain old Python. Feel free to make a pull request for whatever Notebook functionality you want to add.

**Comment by mcarans** [comment]
I will close this as the client does not need this functionality.

**Comment by goatchurchprime** [comment]
Can I ask how the client produces visualization graphs of simulations generated by the code at the moment?  

I'm just asking, in case there is some easier tech that I don't know about.

**Comment by mcarans** [comment]
MEI and HDX developed the visual here: https://data.humdata.org/organization/moving-energy-initiative. Jupyter is beyond the client's technical expertise and our project is now finished.

**Comment by goatchurchprime** [comment]
Well, that doesn't sound particularly logical to me.  

If the client managed to hire a Python developer to construct this model, they might come across a Python data scientist to carry it forwards, and a beautifully polished website front-end with CSV downloads doesn't seem like the best place for them to pick up from.  

But maybe you're right, and the whole project is finished with this, in spite of the statement on the front page:

> This is a highly simplified model of a complex system and is intended as a learning document for the international community - to be built on and improved over time. The model gives indicative estimates of values and should not be viewed as a comprehensive picture, but rather as a starting point for further research.

Just saying.
